name: ci
on:
  workflow_dispatch: #github页面手动触发
  push:
    tags:
      - "v*.*"
env:
  IMAGE_NAME: backend
  DOCKER_REGISTRY: dweizhao
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    outputs:
      tags: ${{ steps.output-id.outputs.v }}
    steps:
      # 拉取代码
      - uses: actions/checkout@v3
      - id: output-id
        run: |
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "v=${VERSION}" >> $GITHUB_OUTPUT
      # java环境
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          # 缓存gradle，若是使用maven构建，改为maven即可，具体可查看 https://github.com/actions/setup-java
          cache: maven
      # 打包
      - name: maven Build
        run: mvn clean source:jar -DskipTests=true package
      # Docker配置qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Docker配置多平台环境
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      # 登录镜像仓库
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      # 生成名称和版本，例如 seepine/springboot-demo ，由发布 v1.2.5 触发，则分别为
      # REPO_NAME=springboot-demo
      # REPO_VERSION=1.2.5
      - name: Get Meta
        id: meta
        run: |
          echo REPO_NAME=$(echo ${GITHUB_REPOSITORY} | awk -F"/" '{print $2}') >> $GITHUB_OUTPUT
          echo REPO_VERSION=$(echo ${{ github.ref }} | awk -F"/" '{print $3}' | awk -F"v" '{print $2}') >> $GITHUB_OUTPUT          
      # 打包构建
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          # 即最终打包成例如 dweizhao/backend:latest
          # 和 dweizhao/backend:1.2.5
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.REPO_VERSION }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest